export const listingsData = [
  {
    id: 1,
    title: "Luxury Sunset 3BR Villa w/ BEACH access",
    description: "This is one of the few places in the area with free parking.",
    imageSrc: "/assets/houses/1.jpg",
    locationValue: "US",
    category: "Beach",
    price: "165",
    guestCount: 4,
    roomCount: 2,
    bathroomCount: 1,
    user: {
      name: "Diwash",
      image: "/assets/user1.png",
    },
  },
  {
    id: 2,
    title: "Villa Leelawadee - With Phang Nga Bay View",
    description:
      "A common area with wifi that’s well-suited for working.Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
    imageSrc: "/assets/houses/2.jpg",
    locationValue: "JP",
    category: "Windmills",
    price: 219,
    guestCount: 2,
    roomCount: 1,
    bathroomCount: 1,
    user: {
      name: "Manish",
    },
  },
  {
    id: 3,
    title: "Aura House 2bds Eco Bamboo House, Pool, River View",
    description:
      "Consisting of Villa Ruby and Villa Emerald, this beautiful vacation rental is perfect for large group getaways in Northern Chaweng. Located in the Narayan Heights neighborhood, Villa Amylia captures scenic vistas of the ocean, islands, and mountains. The villa is just 250m from the beach and has 2 swimming pools, space for 20, and a rooftop terrace that can host up to 40 guests.",
    imageSrc: "/assets/houses/3.jpg",
    locationValue: "DE",
    category: "Modern",
    price: 999,
    guestCount: 8,
    roomCount: 4,
    bathroomCount: 4,
    user: {
      name: "Aakash",
    },
  },
  {
    id: 4,
    title: "Magnificent Treehouse with Valley View| Tandi",
    description:
      "You can check in with the doorman.This is one of the few places in the area with a pool.",
    imageSrc: "/assets/houses/4.jpg",
    locationValue: "IN",
    category: "Countryside",
    price: 362,
    guestCount: 1,
    roomCount: 1,
    bathroomCount: 1,
    user: {
      name: "Niroj",
    },
  },
  {
    id: 5,
    title: "Luxe 1 BDR Romantic hideaway Private Villa Ubud",
    description:
      "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.100% of recent guests gave the location a 5-star rating.100% of recent guests gave the check-in process a 5-star rating.",
    imageSrc: "/assets/houses/5.jpg",
    locationValue: "BR",
    category: "Pools",
    price: 248,
    guestCount: 12,
    roomCount: 12,
    bathroomCount: 8,
    user: {
      name: "Aayush",
    },
  },
  {
    id: 6,
    title: "Villa Moon Shadow",
    description:
      'In the heart of Salento, immersed in a centuries-old olive grove, the "Masseria Quadrelli" is located just 10 km from Otranto and a few km from Santa Cesarea Terme, a well-known resort known for its spa and the beautiful sea. It is immersed in a centuries-old garden of typical Mediterranean trees and essences, such as olive trees, oleanders, strawberries, figs, bucanville, broom, which perfume the environment around the spectacular pool of irregular shape, with built-in whirlpool.',
    imageSrc: "/assets/houses/6.jpg",
    locationValue: "TH",
    category: "Islands",
    price: 683,
    guestCount: 1,
    roomCount: 1,
    bathroomCount: 1,
    user: {
      name: "Sudip",
    },
  },
  {
    id: 7,
    title: "Willow Way - A Dream Wooden Cottage in Himalayas",
    description:
      "The Dream Wooden Cottage has been made out of love for the mountains and a wish to slow down the pace of life. Ideal for family and 'me' time, this is a home away from a home; tucked away in the lush green Himalayan Valley Village Chachogi, 3km away from the Town of Naggar in Himachal Pradesh",
    imageSrc: "/assets/houses/7.jpg",
    locationValue: "NP",
    category: "Lake",
    price: 249,
    guestCount: 1,
    roomCount: 1,
    bathroomCount: 1,
    user: {
      name: "Rostik",
    },
  },
  {
    id: 8,
    title: "Villa Leopold Villa Veneta with swimming pool",
    description:
      "Nature and rustic luxury in one self-contained space best describes Treehouse de Valentine. Unconventional for the right reasons, this dream house is the perfect nest away from the hustle and bustle of Cebu City.",
    imageSrc: "/assets/houses/8.jpg",
    locationValue: "PK",
    category: "Caves",
    price: 815,
    guestCount: 1,
    roomCount: 1,
    bathroomCount: 1,
    user: {
      name: "Sangam",
    },
  },
  {
    id: 9,
    title: "Whispering Pines Cottages| Treehut| Tandi",
    description:
      "It is an old traditional wooden house located in a tranquil valley of Rakchham , a perfect stay option for Artists and Serenity lovers...",
    imageSrc: "/assets/houses/9.jpg",
    locationValue: "SR",
    category: "Camping",
    price: 801,
    guestCount: 1,
    roomCount: 1,
    bathroomCount: 1,
    user: {
      name: "Prakash",
    },
  },
  {
    id: 10,
    title: "Emotional Healing in Lee Cheon-si, Seoul",
    description:
      "It is an arched bungalow-shaped independent house with 20m2 of interior space (bedroom, kitchen, bathroom) and 40m2 wooden decks on the second floor. It's a national park, home to fireflies and maintains the best natural environment in which to live across the frontal creek. Ideal for family breaks and team-based MT, the dome greenhouse offers a day workshop for up to 30 people.",
    imageSrc: "/assets/houses/2.jpg",
    locationValue: "CN",
    category: "Skiing",
    price: 369,
    guestCount: 1,
    roomCount: 1,
    bathroomCount: 1,
    user: {
      name: "Sammy",
    },
  },
];
